services:
  amneziawg:
    image: amneziavpn/amneziawg-go:latest
    container_name: amneziawg
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    # sysctls set on host level (not allowed with network_mode: host)
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config:/etc/amneziawg
      - ./peers:/etc/amneziawg/peers
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /bin/sh
    command: ['/entrypoint.sh']
